version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: smarthub-db
    environment:
      - 'POSTGRES_DB=smarthub_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=smarthub'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
